### ISSUE TITLE
MiTM Device not detecting the correct IP of the target

### ISSUE THREAD

**Issue by Aajnow** [RoganDawes/slimjim#1]
Issue:

I have followed the blog @ https://sensepost.com/blog/2020/making-the-perfect-red-team-dropbox-part-2/
The issue I am facing is that when I run the slimjim script, it detected the Victim IP address incorrectly.

I have the target set to get the IP via DHCP and when I have the MiTM device setup in between the target and the router, it detects the APIPA IP address, since the target is currently missing an IP as it is yet to reach the DHCP server.
![image](https://user-images.githubusercontent.com/10479886/131223271-ef0e8a58-f20b-4d2a-96f4-a5cbc87b997b.png)
When I ping a device on the network, the source IP is that APIPA IP.

Once I set a static IP on the target, it works fine (victim IP correctly detected as the static IP) and the traffic injection works with  the source IP for all injected traffic now set to the target IP.
Can you please check and advise what am I missing here.

**Comment by RoganDawes** [comment]
It’s possible that the tcpdump filters are not excluding the APIPA range.
Perhaps try updating the filters to see if that helps?

**Comment by RoganDawes** [comment]
Update here:

https://github.com/RoganDawes/slimjim/blob/d565e3497d2c63a0fc917595e754d49d8b326e18/slimjim#L121

**Comment by Aajnow** [comment]
Thank you, it worked!

**Comment by RoganDawes** [comment]
Any to submit a pr?

**Comment by Aajnow** [comment]
Will do, facing a weird issue now.
The device is correctly injecting traffic with the target IP address, but I am not sure if the traffic is returning back to the virtual interface.

For eg:
As seen in the image below, I am trying to ping another machine on the network from the pitm interface.
When I run a tcpdump on the .17 machine, I see a request and reply for ICMP, but the ping command fails to report it as successful ping on the MiTm device.
Same with SSH, I don't get a session back.

![image](https://user-images.githubusercontent.com/10479886/131225283-c6991a8e-3bee-4bac-b29c-2dd25760ee1f.png)

i get this error when I ssh into the pitm interface, if its of any help
![image](https://user-images.githubusercontent.com/10479886/131225568-52711d5c-4682-4fb4-8958-b89c0f8ffcaa.png)

**Comment by Aajnow** [comment]
So the above issue got fixed. The 192.168.1..17 machine is a VM and the IP that I had MiTMed ie; 192.168.1..2 was the Host, so the ping packets were sent from the MiTM device but the reply was directly sent to the 192.168.1.2 machine as it was the host machine and the VM (192.168.1.17) used the internal VMNet switch on the host to sent the reply back which went to the real .2 machine

**Comment by RoganDawes** [comment]
Excellent! Glad you figured it out!
